Add attributes.
bastion-rs/agnostik pull request #28
Opened 2020-11-23 15:25 UTC by dvc94ch

I'm happy to transfer the `agnostik-attributes` repo. It's essentially the same as `async-attributes` but using agnostik instead of `async-std`.

2020-11-23 20:51 UTC, Stupremee commented
It's fine if you implement the macros in a new crate `agnostik_derive` in this repository using a cargo workspace

2020-11-23 21:22 UTC, dvc94ch commented
Finally, linux and macos are failing. I don't think ci is actually running on windows either.

2020-11-24 11:39 UTC, Stupremee requested changes

2020-11-24 11:39 UTC, Stupremee commented on attributes/src/lib.rs
> +//! polyfill for it in the mean time.
Change the comments to be more agnostik specific and not about the general async rust eco system

2020-11-24 11:39 UTC, Stupremee commented on attributes/Cargo.toml
> +description = "Experimental language-level polyfills for Async Rust."
Change the description to be specific to agnostik

2020-11-24 11:39 UTC, Stupremee commented on attributes/Cargo.toml
> +authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
Change the authors to either yourself or just `Agnostik Developers`

2020-11-27 08:34 UTC, Stupremee approved these changes

2020-11-27 08:34 UTC, merged

2020-11-27 08:34 UTC, Stupremee commented
Thanks for the PR. I will release a new version now with the new macros

2020-11-27 08:38 UTC, Stupremee commented
Oh, can you add me as an owner for the `agnostik_attributes` crate so I can publish it?

2020-11-27 12:46 UTC, dvc94ch commented
done